[package]
name = "fromage"
description = "Placeholder"
version = "0.0.0"
authors = ["FujiApple <fujiapple852@gmail.com>"]
repository = "https://github.com/fujiapple852/fromage"
license = "Apache-2.0"
edition = "2024"

[dependencies]
